config/routes.rb
Rails.application.routes.draw do
  get 'relatorios/abastecimentos'
  post 'relatorios/abastecimentos'

  get 'relatorios/gastos'
  post 'relatorios/gastos'

  get 'relatorios/info'
  post 'relatorios/info'
  
  get 'relatorios/index'

  get 'relatorios/desempenho'
  post 'relatorios/desempenho'


  devise_for :usuarios, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :calcflex
  resources :dashboard
  resources :marcas
  resources :abastecimentos
  resources :manutencoes
  resources :impostos
  resources :despesas
  resources :veiculos
  resources :formaspagamentos
  resources :tiposveiculos
  resources :combustiveis
  resources :perfisusuarios
  root to: 'dashboard#index'
  get '/relatorios', to: 'relatorios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abastecimento.rb
class Abastecimento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :combustivel
  belongs_to :formaspagamento
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combustivel.rb
class Combustivel < ApplicationRecord
end

app/models/despesa.rb
class Despesa < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/formaspagamento.rb
class Formaspagamento < ApplicationRecord
end

app/models/imposto.rb
class Imposto < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/manutencao.rb
class Manutencao < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/marcas.rb
class Marcas < ApplicationRecord
end

app/models/perfisusuario.rb
class Perfisusuario < ApplicationRecord
end

app/models/tiposveiculo.rb
class Tiposveiculo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :usuario
  belongs_to :marca
  belongs_to :tiposveiculo
end

app/controllers/impostos_controller.rb
class ImpostosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_imposto, only: [:edit, :update, :destroy]

  # GET /impostos
  # GET /impostos.json
  def index
    @veiculos = Veiculo.where(usuario_id: current_usuario)
    @impostos = Imposto.where(:veiculo_id => @veiculos)
  end

  # GET /impostos/new
  def new
    @imposto = Imposto.new
  end

  # GET /impostos/1/edit
  def edit
  end

  # POST /impostos
  # POST /impostos.json
  def create
    @imposto = Imposto.new(imposto_params)

    respond_to do |format|
      if @imposto.save
        format.html { redirect_to impostos_url, notice: 'Imposto criado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @imposto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /impostos/1
  # PATCH/PUT /impostos/1.json
  def update
    respond_to do |format|
      if @imposto.update(imposto_params)
        format.html { redirect_to impostos_url, notice: 'Imposto editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @imposto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impostos/1
  # DELETE /impostos/1.json
  def destroy
    @imposto.destroy
    respond_to do |format|
      format.html { redirect_to impostos_url, notice: 'Imposto excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imposto
      @imposto = Imposto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imposto_params
      params.require(:imposto).permit(:descricao, :valor, :vencimento_dt, :obs, :pago_flag, :formaspagamento_id, :veiculo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calcflex_helper.rb
module CalcflexHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/impostos_helper.rb
module ImpostosHelper
end

app/helpers/manutencoes_helper.rb
module ManutencoesHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/impostos/_form.html.erb
<%= form_for(imposto, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if imposto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imposto.errors.count, "error") %> prohibited this imposto from being saved:</h2>

      <ul>
      <% imposto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row example-row">
    <div class="col-md-3">Descrição:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :descricao, class: 'form-control' %>
            </div>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Valor:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :valor, class: 'form-control inputmask inputmask-decimal valid' %>
            </div>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Data Vencimento:</div> 
      <div class="col-md-9">
       <div class="control-group">
          <div class="controls">
            <div class="input-group">
            <span class="input-group-addon"><i class="ion-android-calendar"></i></span>
            <div class="inputer">
              <div class="input-wrapper">
              <%= f.text_field :vencimento_dt, class: 'form-control bootstrap-daterangepicker-basic valid active' %>
              </div>
            </div>
          </div>
        </div>
       </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Observações:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :obs, class: 'form-control' %>
            </div>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Pago:</div> 
      <div class="col-md-9">
        <div class="switcher">
            <%= f.check_box :pago_flag, hidden: 'hidden' %>
            <label for="imposto_pago_flag"></label>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Forma de Pagamento:</div> 
      <div class="col-md-9">
        <%= f.collection_select(:formaspagamento_id, Formaspagamento.all, :id, :nome, {prompt: "Selecione"}, {class: 'selectpicker', "data-live-search" => "true"}) %>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Veículo:</div> 
      <div class="col-md-9">
        <%= f.collection_select(:veiculo_id, Veiculo.where(usuario_id: current_usuario), :id, :nome, {prompt: "Selecione"}, {class: 'selectpicker', "data-live-search" => "true"}) %>
      </div> 
  </div>

  <div class="form-buttons">
    <div class="row">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Salvar', :class => 'btn btn-blue btn-ripple' %>
        <input type="reset" value="Limpar Campos" class="btn btn-flat btn-danger btn-ripple">
        <a href="<%= impostos_path %>" class="btn btn-flat btn-ripple">Voltar</a>
      </div>
    </div>
  </div>
<% end %>

app/views/impostos/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Impostos</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		<%= render 'form', imposto: @imposto %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/impostos/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Impostos</h4>
            <a class="btn btn-floating btn-teal btn-light-green pull-right" href="<%=new_imposto_path %>">
              <i class="ion-android-add"></i>
            </a>
        </div>
        
      </div><!--.panel-heading-->
      <div class="panel-body">
        <div class="unseen">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th>Veículo</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Data Vencimento</th>
                <th>Imposto Pago</th>
                <th style="width:120px">Ações</th>
            </thead>
            <tbody>
              <% @impostos.sort_by(&:vencimento_dt).reverse!.each do |imposto| %>
                <tr align="center">
                  <td><%= Veiculo.find(imposto.veiculo).nome %></td>
                  <td><%= imposto.descricao %></td>
                  <td align="right">R$ <%= imposto.valor %></td>
                  <td><%= imposto.vencimento_dt %></td>
                  <td align="center">
                    <% if imposto.pago_flag %>
                      <div class="checkboxer">
                        <input type="checkbox" id="pago_<%= imposto.id %>" checked disabled>
                        <label for="pago_<%= imposto.id %>"></label>
                      </div>
                    <% else %>
                      <div class="checkboxer">
                        <input type="checkbox" id="pago_<%= imposto.id %>" disabled>
                        <label for="pago_<%= imposto.id %>"></label>
                      </div>
                    <% end %>
                  </td>
                  
                  <td align="center">
                    <a href="<%= edit_imposto_path(imposto) %>" class="btn btn-default btn-ripple" title="Editar registro">
                      <span class="ion-edit">
                    </a>
                    <a class="btn btn-default btn-red btn-ripple" title="Remover registro" data-toggle="modal" data-target="#deleteModal_<%= imposto.id %>">
                      <span class="ion-android-delete"></span>
                    </a>
                  </td>
                </tr>
                <div class="modal scale fade" id="deleteModal_<%= imposto.id %>" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Karango WepApp</h4>
                      </div>
                      <div class="modal-body">
                        Deseja realmente excluir este registro?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-flat btn-ripple" data-dismiss="modal">Não</button>
                        <%= button_to "Sim", imposto, :method=>:delete, class: 'btn btn-flat btn-danger btn-ripple' %>
                      </div>
                    </div><!--.modal-content-->
                  </div><!--.modal-dialog-->
                </div><!--.modal-->
              <% end %>
            </tbody>
          </table>
        </div><!--.unseen-->
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/impostos/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Impostos</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		<%= render 'form', imposto: @imposto %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>