config/routes.rb
Rails.application.routes.draw do
  get 'relatorios/abastecimentos'
  post 'relatorios/abastecimentos'

  get 'relatorios/gastos'
  post 'relatorios/gastos'

  get 'relatorios/info'
  post 'relatorios/info'
  
  get 'relatorios/index'

  get 'relatorios/desempenho'
  post 'relatorios/desempenho'


  devise_for :usuarios, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :calcflex
  resources :dashboard
  resources :marcas
  resources :abastecimentos
  resources :manutencoes
  resources :impostos
  resources :despesas
  resources :veiculos
  resources :formaspagamentos
  resources :tiposveiculos
  resources :combustiveis
  resources :perfisusuarios
  root to: 'dashboard#index'
  get '/relatorios', to: 'relatorios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abastecimento.rb
class Abastecimento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :combustivel
  belongs_to :formaspagamento
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combustivel.rb
class Combustivel < ApplicationRecord
end

app/models/despesa.rb
class Despesa < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/formaspagamento.rb
class Formaspagamento < ApplicationRecord
end

app/models/imposto.rb
class Imposto < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/manutencao.rb
class Manutencao < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/marcas.rb
class Marcas < ApplicationRecord
end

app/models/perfisusuario.rb
class Perfisusuario < ApplicationRecord
end

app/models/tiposveiculo.rb
class Tiposveiculo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :usuario
  belongs_to :marca
  belongs_to :tiposveiculo
end

app/controllers/abastecimentos_controller.rb
class AbastecimentosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_abastecimento, only: [:edit, :update, :destroy]

  # GET /abastecimentos
  # GET /abastecimentos.json
  def index
    @veiculos = Veiculo.where(usuario_id: current_usuario)
    @abastecimentos = Abastecimento.where(:veiculo_id => @veiculos)
  end
  
  # GET /abastecimentos/new
  def new
    @abastecimento = Abastecimento.new
  end

  # GET /abastecimentos/1/edit
  def edit
  end

  # POST /abastecimentos
  # POST /abastecimentos.json
  def create
    @abastecimento = Abastecimento.new(abastecimento_params)

    respond_to do |format|
      if @abastecimento.save
        format.html { redirect_to abastecimentos_url, notice: 'Abastecimento criado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @abastecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abastecimentos/1
  # PATCH/PUT /abastecimentos/1.json
  def update
    respond_to do |format|
      if @abastecimento.update(abastecimento_params)
        format.html { redirect_to abastecimentos_url, notice: 'Abastecimento editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @abastecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abastecimentos/1
  # DELETE /abastecimentos/1.json
  def destroy
    @abastecimento.destroy
    respond_to do |format|
      format.html { redirect_to abastecimentos_url, notice: 'Abastecimento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abastecimento
      @abastecimento = Abastecimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abastecimento_params
      params.require(:abastecimento).permit(:abastecimento_dt, :odometro, :precolitro, :precototal, :obs, :veiculo_id, :completou_flag, :combustivel_id, :formaspagamento_id)
    end
end

app/helpers/abastecimentos_helper.rb
module AbastecimentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calcflex_helper.rb
module CalcflexHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/impostos_helper.rb
module ImpostosHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/abastecimentos/_form.html.erb
<%= form_for(abastecimento, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if abastecimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(abastecimento.errors.count, "error") %> prohibited this abastecimento from being saved:</h2>

      <ul>
      <% abastecimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row example-row">
    <div class="col-md-3">Veículo:</div> 
      <div class="col-md-9">
        <%= f.collection_select(:veiculo_id, Veiculo.where(usuario_id: current_usuario), :id, :nome, {prompt: "Selecione"}, {class: 'selectpicker', "data-live-search" => "true"}) %>
      </div> 
  </div>
  
  <div class="row example-row">
    <div class="col-md-3">Combustível:</div> 
      <div class="col-md-9">
        <%= f.collection_select(:combustivel_id, Combustivel.all, :id, :nome, {prompt: "Selecione"}, {class: 'selectpicker', "data-live-search" => "true"}) %>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Completou:</div> 
      <div class="col-md-9">
        <div class="switcher">
            <%= f.check_box :completou_flag, hidden: 'hidden' %>
            <label for="abastecimento_completou_flag"></label>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Preço Litro:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :precolitro, class: 'form-control inputmask inputmask-decimal valid' %>
            </div>
          </div>
      </div> 
  </div>
  
  <div class="row example-row">
    <div class="col-md-3">Preço Total:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :precototal, class: 'form-control inputmask inputmask-decimal valid' %>
            </div>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Odometro:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.number_field :odometro, class: 'form-control payment-restrict valid' %>
            </div>
          </div>
      </div> 
  </div>
  
  <div class="row example-row">
    <div class="col-md-3">Data Abastecimento:</div> 
      <div class="col-md-9">
       <div class="control-group">
          <div class="controls">
            <div class="input-group">
            <span class="input-group-addon"><i class="ion-android-calendar"></i></span>
            <div class="inputer">
              <div class="input-wrapper">
              <%= f.text_field :abastecimento_dt, class: 'form-control bootstrap-daterangepicker-basic valid active' %>
              </div>
            </div>
          </div>
        </div>
       </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Forma de Pagamento:</div> 
      <div class="col-md-9">
        <%= f.collection_select(:formaspagamento_id, Formaspagamento.all, :id, :nome, {prompt: "Selecione"}, {class: 'selectpicker', "data-live-search" => "true"}) %>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Observações:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_area :obs, class: 'form-control', rows: '4' %>
            </div>
          </div>
      </div> 
  </div>
<div class="form-buttons">
    <div class="row">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Salvar', :class => 'btn btn-blue btn-ripple' %>
        <input type="reset" value="Limpar Campos" class="btn btn-flat btn-danger btn-ripple">
        <a href="<%= abastecimentos_path %>" class="btn btn-flat btn-ripple">Voltar</a>
      </div>
    </div>
  </div>
<% end %>

app/views/abastecimentos/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Abastecimentos</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		<%= render 'form', abastecimento: @abastecimento %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/abastecimentos/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Abastecimentos</h4>
            <a class="btn btn-floating btn-teal btn-light-green pull-right" href="<%=new_abastecimento_path %>">
              <i class="ion-android-add"></i>
            </a>
        </div>
        
      </div><!--.panel-heading-->
      <div class="panel-body">
        <div class="unseen">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th>Veículo</th>
                <th>Data Abastecimento</th>
                <th>Odometro</th>
                <th>Preço Litro</th>
                <th>Preço Total</th>
                <th>Completou</th>
                <th>Combustível</th>
                <th style="width:120px">Ações</th>
            </thead>
            <tbody>
              <% @abastecimentos.sort_by(&:abastecimento_dt).reverse!.each do |abastecimento| %>
                <tr>
                  <td align="center"><%= Veiculo.find(abastecimento.veiculo).nome %></td>
                  <td align="center"><%= abastecimento.abastecimento_dt %></td>
                  <td align="center"><%= abastecimento.odometro %></td>
                  <td align="right">R$ <%= abastecimento.precolitro %></td>
                  <td align="right">R$ <%= abastecimento.precototal %></td>
                  <td align="center">
                    <% if abastecimento.completou_flag %>
                      <div class="checkboxer">
                        <input type="checkbox" id="completou_<%= abastecimento.id %>" checked disabled>
                        <label for="completou_<%= abastecimento.id %>"></label>
                      </div>
                    <% else %>
                      <div class="checkboxer">
                        <input type="checkbox" id="completou_<%= abastecimento.id %>" disabled>
                        <label for="completou_<%= abastecimento.id %>"></label>
                      </div>
                    <% end %>
                  </td>
                  <td align="center"><%= Combustivel.find(abastecimento.combustivel).nome %></td>
                  
                  <td align="center">
                    <a href="<%= edit_abastecimento_path(abastecimento) %>" class="btn btn-default btn-ripple" title="Editar registro">
                      <span class="ion-edit">
                    </a>
                    <a class="btn btn-default btn-red btn-ripple" title="Remover registro" data-toggle="modal" data-target="#deleteModal_<%= abastecimento.id %>">
                      <span class="ion-android-delete"></span>
                    </a>
                  </td>
                </tr>
                <div class="modal scale fade" id="deleteModal_<%= abastecimento.id %>" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Karango WepApp</h4>
                      </div>
                      <div class="modal-body">
                        Deseja realmente excluir este registro?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-flat btn-ripple" data-dismiss="modal">Não</button>
                        <%= button_to "Sim", abastecimento, :method=>:delete, class: 'btn btn-flat btn-danger btn-ripple' %>
                      </div>
                    </div><!--.modal-content-->
                  </div><!--.modal-dialog-->
                </div><!--.modal-->
              <% end %>
            </tbody>
          </table>
        </div><!--.unseen-->
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/abastecimentos/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Abastecimentos</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		<%= render 'form', abastecimento: @abastecimento %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>