config/routes.rb
Rails.application.routes.draw do
  get 'relatorios/abastecimentos'
  post 'relatorios/abastecimentos'

  get 'relatorios/gastos'
  post 'relatorios/gastos'

  get 'relatorios/info'
  post 'relatorios/info'
  
  get 'relatorios/index'

  get 'relatorios/desempenho'
  post 'relatorios/desempenho'


  devise_for :usuarios, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :calcflex
  resources :dashboard
  resources :marcas
  resources :abastecimentos
  resources :manutencoes
  resources :impostos
  resources :despesas
  resources :veiculos
  resources :formaspagamentos
  resources :tiposveiculos
  resources :combustiveis
  resources :perfisusuarios
  root to: 'dashboard#index'
  get '/relatorios', to: 'relatorios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abastecimento.rb
class Abastecimento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :combustivel
  belongs_to :formaspagamento
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combustivel.rb
class Combustivel < ApplicationRecord
end

app/models/despesa.rb
class Despesa < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/formaspagamento.rb
class Formaspagamento < ApplicationRecord
end

app/models/imposto.rb
class Imposto < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/manutencao.rb
class Manutencao < ApplicationRecord
  belongs_to :formaspagamento
  belongs_to :veiculo
end

app/models/marca.rb
class Marca < ApplicationRecord
end

app/models/marcas.rb
class Marcas < ApplicationRecord
end

app/models/perfisusuario.rb
class Perfisusuario < ApplicationRecord
end

app/models/tiposveiculo.rb
class Tiposveiculo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :usuario
  belongs_to :marca
  belongs_to :tiposveiculo
end

app/controllers/perfisusuarios_controller.rb
class PerfisusuariosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_perfisusuario, only: [:edit, :update, :destroy]

  # GET /perfisusuarios
  # GET /perfisusuarios.json
  def index
    @perfisusuarios = Perfisusuario.all
  end
  
  # GET /perfisusuarios/new
  def new
    @perfisusuario = Perfisusuario.new
  end

  # GET /perfisusuarios/1/edit
  def edit
  end

  # POST /perfisusuarios
  # POST /perfisusuarios.json
  def create
    @perfisusuario = Perfisusuario.new(perfisusuario_params)

    respond_to do |format|
      if @perfisusuario.save
        format.html { redirect_to perfisusuarios_url, notice: 'Perfil de Usuário criado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @perfisusuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfisusuarios/1
  # PATCH/PUT /perfisusuarios/1.json
  def update
    respond_to do |format|
      if @perfisusuario.update(perfisusuario_params)
        format.html { redirect_to perfisusuarios_url, notice: 'Perfil de Usuário editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @perfisusuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfisusuarios/1
  # DELETE /perfisusuarios/1.json
  def destroy
    @perfisusuario.destroy
    respond_to do |format|
      format.html { redirect_to perfisusuarios_url, notice: 'Perfil de Usuário excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfisusuario
      @perfisusuario = Perfisusuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfisusuario_params
      params.require(:perfisusuario).permit(:nome, :admin_flag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calcflex_helper.rb
module CalcflexHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/impostos_helper.rb
module ImpostosHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/perfisusuarios_helper.rb
module PerfisusuariosHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/perfisusuarios/_form.html.erb
<%= form_for(perfisusuario, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if perfisusuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perfisusuario.errors.count, "error") %> prohibited this perfisusuario from being saved:</h2>

      <ul>
      <% perfisusuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row example-row">
    <div class="col-md-3">Nome:</div> 
      <div class="col-md-9">
        <div class="inputer">
            <div class="input-wrapper">
              <%= f.text_field :nome, class: 'form-control' %>
            </div>
          </div>
      </div> 
  </div>

  <div class="row example-row">
    <div class="col-md-3">Admin:</div> 
      <div class="col-md-9">
        <div class="switcher">
            <%= f.check_box :admin_flag, hidden: 'hidden' %>
            <label for="perfisusuario_admin_flag"></label>
          </div>
      </div> 
  </div>

  <div class="form-buttons">
    <div class="row">
      <div class="col-md-offset-3 col-md-9">
        <%= f.submit 'Salvar', :class => 'btn btn-blue btn-ripple' %>
        <input type="reset" value="Limpar Campos" class="btn btn-flat btn-danger btn-ripple">
        <a href="<%= perfisusuarios_path %>" class="btn btn-flat btn-ripple">Voltar</a>
      </div>
    </div>
  </div>
<% end %>

app/views/perfisusuarios/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Perfis de Usuários</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		    <%= render 'form', perfisusuario: @perfisusuario %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/perfisusuarios/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Perfis de Usuários</h4>
            <a class="btn btn-floating btn-teal btn-light-green pull-right" href="<%=new_perfisusuario_path %>">
              <i class="ion-android-add"></i>
            </a>
        </div>
        
      </div><!--.panel-heading-->
      <div class="panel-body">
        <div class="unseen">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Administrador</th>
                <th style="width:120px">Ações</th>
            </thead>
            <tbody>
              <% @perfisusuarios.each do |perfisusuario| %>
                <tr>
                  <td><%= perfisusuario.id %></td>
                  <td><%= perfisusuario.nome %></td>
                  <td align="center">
                    <% if perfisusuario.admin_flag %>
                    <div class="checkboxer">
                      <input type="checkbox" id="admin_<%= perfisusuario.id %>" checked disabled>
                      <label for="admin_<%= perfisusuario.id %>"></label>
                    </div>
                  <% else %>
                    <div class="checkboxer">
                      <input type="checkbox" id="admin_<%= perfisusuario.id %>" disabled>
                      <label for="admin_<%= perfisusuario.id %>"></label>
                    </div>
                  <% end %>
                </td>
  
                  <td align="center">
                    <a href="<%= edit_perfisusuario_path(perfisusuario) %>" class="btn btn-default btn-ripple" title="Editar registro">
                      <span class="ion-edit">
                    </a>
                    <a class="btn btn-default btn-red btn-ripple" title="Remover registro" data-toggle="modal" data-target="#deleteModal_<%= perfisusuario.id %>">
                      <span class="ion-android-delete"></span>
                    </a>
                  </td>
                </tr>
                <div class="modal scale fade" id="deleteModal_<%= perfisusuario.id %>" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Karango WepApp</h4>
                      </div>
                      <div class="modal-body">
                        Deseja realmente excluir este registro?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-flat btn-ripple" data-dismiss="modal">Não</button>
                        <%= button_to "Sim", perfisusuario, :method=>:delete, class: 'btn btn-flat btn-danger btn-ripple' %>
                      </div>
                    </div><!--.modal-content-->
                  </div><!--.modal-dialog-->
                </div><!--.modal-->
              <% end %>
            </tbody>
          </table>
        </div><!--.unseen-->
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>

app/views/perfisusuarios/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <div class="panel-title">
          <h4>Cadastro de Perfis de Usuários</h4>
      </div>
      </div><!--.panel-heading-->
      <div class="panel-body">
		    <%= render 'form', perfisusuario: @perfisusuario %>
      </div><!--.panel-body-->
    </div><!--.panel-->
  </div><!--.col-md-12-->
</div>